export const AUTH = {
  START: "LOGIN_START",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL"
};

export const REGISTER = {
  START: "START_REGISTER",
  SUCCESS: "SUCCESS_REGISTER",
  FAIL: "FAIL_REGISTER"
}