const REGISTER = {
  START: "REGISTER_START",
  SUCCESS: "REGISTER_SUCCESS",
  FAIL: "REGISTER_FAIL"
};
const LOGIN = {
  START: "LOGIN_START",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL"
};
const LOGOUT = {
  START: "LOGOUT_START",
  SUCCESS: "LOGOUT_SUCCESS",
  FAIL: "LOGOUT_FAIL"
};

export { REGISTER, LOGIN, LOGOUT };
