export const LOGIN = {
  START: "LOGIN_START",
  SUCCESS: "LOGIN_SUCCESS",
  FAIL: "LOGIN_FAIL"
};

export const REGISTER = {
  START: "REGISTER_START",
  SUCCESS: "REGISTER_SUCCESS",
  FAIL: "REGISTER_FAIL"
};
